### ISSUE TITLE
[Todo]

### ISSUE THREAD

**Issue by DannyvanderJagt** [TheSuitcase/Pyramid#1]
Core:
- [x] Clean up the code a little
- [x] ~~Update Inquirer delimiter and color~~
- [x] Provide the possibility for action feedback (for action:progressbar)
- [x] ~~Add `delay` to core~~
- [x] Add `addAction` to Pyramid for adding a new action.
- [x] Add `removeAction` to Pyramid for deleting user added actions

Command:
- [x] Process the `required` arguments
- [x] Process the `optional` arguments
- [x] Process the `option` arguments
- [x] ~~Implement `subcommands`~~
- [x] ~~Implement `autocomplete`~~
- [x] Implement `validate` in `required`, `optional` and `options`
- [x] Implement `exit` callback
- [x] Implement `validate` callback
- [x] Implement `action` callback

Actions:
- [ ] Progress bar
- [ ] Load spinner

Documentation:
- [ ] General
- [ ] Command
- [ ] For each action
- [ ] Create your own actions
- [ ] Contribution
- [ ] Changelog

Examples:
- [ ] Create a general example
- [ ] Create an advanced example
- [ ] Create a example with an custom action. 
- [ ] Add an example for each build-in action.

Tests:
- [ ] Write (almost) all the tests
- [ ] Add github integration for tests

Npm:
- [ ] Get in touch with the owner of the npm namespace
- [ ] Publish on npm

Issues:
- [ ] Colors are not checked against `Chalk`
- [ ] Replace `cli-colors` with something else that works.
